language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install setuptools
  - sudo python3 setup.py install
# tests should run from the tests directory
before_script: cd sciope/tests
# command to run tests
script: py.test
